[build]
  functions = "./build-netlify-functions"
  publish = "./build"
  command = "npm run build"

[[redirects]]
  from = "/dropbox-webhook"
  to = "https://netlibox.netlify.com/.netlify/functions/dropbox-webhook-2"
  status = 200