[build]
  functions = "./build-netlify-functions"
  publish = "./build"
  command = "npm run build"

[[redirects]]
  from = "/dropbox-webhook"
  # Once you get your site's `/dropbox-webhook` path verified webhook URI in the
  # Dropbox API, you'll want to delete this particular `to` line and uncomment
  # the one below it, as we won't need our function endpoint anymore.
  # to = "/.netlify/functions/dropbox-webhook"
  to = "https://api.netlify.com/build_hooks/5b9bce1a02ed83494cbf1e58"
  status = 200